application: smgnsanch
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
  expiration: 0
- url: /flowers-try-3-smaller.png
  static_files: flowers-try-3-smaller.png
  upload: flowers-try-3-smaller.png
- url: /sarahandneil.png
  static_files: sarahandneil.png
  upload: sarahandneil.png
- url: /left-thing-small.png
  static_files: left-thing-small.png
  upload: left-thing-small.png
