application: akshayandanna
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
  expiration: 0
- url: /img
  static_dir: img
- url: /css
  static_dir: css
  